version: '2'

services:
  pulsar:
    image: "apachepulsar/pulsar:2.8.3"
    ports:
      - "6650:6650"
      - "8080:8080"
    command: ["bin/pulsar", "standalone"]
  # nginx:
  #   image: 'nginx'
  #   ports:
  #     - '8001:443'
  #     - '8002:80'
  #   volumes:
  #     - './nginx-test.conf:/etc/nginx/nginx.conf'
  #     - './localhost.crt:/certs/localhost.crt'
  #     - './localhost.key:/certs/localhost.key'
  dashboard:
    container_name: dashboard 
    image: datastax/pulsar-admin-console
    expose:
      - '80'
    # depends_on:
    #   - nginx
    environment:
      PORT: "80"
